### PR TITLE
Add pixel fireplace screensaver

### PR DESCRIPTION
**Pull request by muffinista**
This adds the screensaver from https://github.com/muffinista/before-dawn/issues/197

Hey @lexterror let me know if you're cool with this!

### CODE REVIEW

**Comment by lexterror** [comment]
Oh hi,

Ive been off the net for a while...

Youll be glad to hear Ive drastically improved and finalized the pixel fireplace screensaver.

Here is version 6.0 final: Thank you!

Feel free to add this one:

[fireplace6.0final.zip](https://github.com/user-attachments/files/16258519/fireplace6.0final.zip)

**Comment by muffinista** [comment]
Awesome!

**Comment by lexaterra** [comment]
Hi muffinista, @muffinista 

Its me LexTerror,

I got a new number from T-Mobile and got locked out of gmail&yahoo.

I updated this last week the pixel fireplace. 

Please check out this youtube vid and let me know what you think? If you like it, I will post my final script of the fireplace. 

https://youtu.be/GyZ8tvOSna0?si=yPKO_OsD9OosFMuX

Thank you!

**Comment by lexaterra** [comment]
Ive abandoned the pixel fireplace project. Sorry!

**Pull request merged**
